3.3.1  simple self-attention mechanism without weights

In [2]:
import torch

In [3]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [6]:
input_query = inputs[1]

In [7]:
torch.dot(input_query, inputs[0])

tensor(0.9544)

In [12]:
input_query.view(1, -1),

(tensor([[0.5500, 0.8700, 0.6600]]),)

In [23]:
attention_scores = torch.empty(inputs.shape[0])

In [24]:
attention_scores = torch.matmul(inputs, input_query.view(1, -1).transpose(0, 1))

In [29]:
attention_scores.transpose(0,1)

tensor([[0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865]])

In [30]:
attention_weights = torch.softmax(attention_scores, dim=0)

In [31]:
attention_weights.transpose(0,1)

tensor([[0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581]])

In [34]:
torch.sum(inputs, dim = 0)

tensor([2.5900, 3.5000, 3.1700])

In [36]:
context_vector = torch.multiply(attention_weights, inputs).sum(dim = 0)

In [37]:
context_vector

tensor([0.4419, 0.6515, 0.5683])

In [38]:
attention_scores = torch.matmul(inputs, inputs.transpose(0, 1))

In [40]:
attention_weights = torch.softmax(attention_scores, dim = 1)

In [41]:
attention_weights

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [42]:
context_vectors = torch.matmul(attention_weights, inputs)

In [43]:
context_vectors

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])